import { readFileSync } from "fs";
import { join } from "path";
import { type NextRequest } from "next/server";

interface BusStop {
  id: string;
  name: string;
  lat: number;
  lon: number;
  indicator: string;
}

// Loaded once per server process from the file generated by scripts/download-bus-stops.mjs
let STOPS: BusStop[] = [];
try {
  STOPS = JSON.parse(readFileSync(join(process.cwd(), "lib/bus-stops.json"), "utf-8"));
} catch {
  // File absent or empty — will fall back to live TfL search below
}

export async function GET(request: NextRequest) {
  const q = request.nextUrl.searchParams.get("q")?.trim() ?? "";
  if (q.length < 2) return Response.json([]);

  if (STOPS.length > 0) {
    const lower = q.toLowerCase();
    const results = STOPS.filter(
      (s) => s.name.toLowerCase().includes(lower) || s.indicator.toLowerCase().includes(lower),
    ).slice(0, 20);
    return Response.json(results);
  }

  // Static file not populated yet — proxy TfL's own search endpoint
  const apiKey = process.env.TFL_API_KEY;
  if (!apiKey) return Response.json([]);

  const url = new URL(`https://api.tfl.gov.uk/StopPoint/Search/${encodeURIComponent(q)}`);
  url.searchParams.set("modes", "bus");
  url.searchParams.set("app_key", apiKey);

  const res = await fetch(url.toString(), { next: { revalidate: 86400 } });
  if (!res.ok) return Response.json([]);

  const data = await res.json();
  const results: BusStop[] = (data.matches ?? []).slice(0, 20).map(
    (m: { id: string; name: string; lat: number; lon: number }) => ({
      id: m.id,
      name: m.name,
      lat: m.lat,
      lon: m.lon,
      indicator: "",
    }),
  );

  return Response.json(results, {
    headers: { "Cache-Control": "public, max-age=86400" },
  });
}
